// Generated by tools/gen_characters.py — do not edit by hand.
//
// The catalogue is fifty-seven characters with a dozen fields
// each. Transcribing that into a second language by hand is a
// way of introducing mistakes rather than a way of porting, so
// the data is generated and only the logic is written twice.
//
// A field is present only when it differs from the ordinary
// case, so what you read here is what is unusual about each
// character.

export const DATA = {
 "characters": {
  "Washerwoman": {
   "id": "washerwoman",
   "name": "Washerwoman",
   "team": "townsfolk",
   "wake": [
    "first"
   ],
   "nights": "first",
   "first_night": 33
  },
  "Librarian": {
   "id": "librarian",
   "name": "Librarian",
   "team": "townsfolk",
   "wake": [
    "first"
   ],
   "nights": "first",
   "first_night": 34
  },
  "Investigator": {
   "id": "investigator",
   "name": "Investigator",
   "team": "townsfolk",
   "wake": [
    "first"
   ],
   "nights": "first",
   "first_night": 35
  },
  "Chef": {
   "id": "chef",
   "name": "Chef",
   "team": "townsfolk",
   "wake": [
    "first"
   ],
   "nights": "first",
   "first_night": 36
  },
  "Empath": {
   "id": "empath",
   "name": "Empath",
   "team": "townsfolk",
   "wake": [
    "every"
   ],
   "nights": "every",
   "first_night": 37,
   "other_night": 53
  },
  "FortuneTeller": {
   "id": "fortuneteller",
   "name": "Fortune Teller",
   "team": "townsfolk",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every",
   "first_night": 38,
   "other_night": 54
  },
  "Undertaker": {
   "id": "undertaker",
   "name": "Undertaker",
   "team": "townsfolk",
   "wake": [
    "every",
    "other",
    "sometimes"
   ],
   "nights": "conditional",
   "other_night": 55
  },
  "Monk": {
   "id": "monk",
   "name": "Monk",
   "team": "townsfolk",
   "wake": [
    "every",
    "other"
   ],
   "chooses": true,
   "nights": "other",
   "other_night": 12
  },
  "Ravenkeeper": {
   "id": "ravenkeeper",
   "name": "Ravenkeeper",
   "team": "townsfolk",
   "wake": [
    "never",
    "sometimes"
   ],
   "chooses": true,
   "nights": "conditional",
   "other_night": 52
  },
  "Virgin": {
   "id": "virgin",
   "name": "Virgin",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "Alsaahir": {
   "id": "alsaahir",
   "name": "Alsaahir",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "Balloonist": {
   "id": "balloonist",
   "name": "Balloonist",
   "team": "townsfolk",
   "wake": [
    "every",
    "first"
   ],
   "setup": [
    {
     "townsfolk": -1,
     "outsider": 1
    },
    {}
   ],
   "nights": "every",
   "first_night": 45,
   "other_night": 62
  },
  "Acrobat": {
   "id": "acrobat",
   "name": "Acrobat",
   "team": "townsfolk",
   "wake": [
    "every",
    "other"
   ],
   "chooses": true,
   "nights": "other",
   "other_night": 39
  },
  "Farmer": {
   "id": "farmer",
   "name": "Farmer",
   "team": "townsfolk",
   "wake": [
    "never"
   ],
   "other_night": 48
  },
  "Slayer": {
   "id": "slayer",
   "name": "Slayer",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "Soldier": {
   "id": "soldier",
   "name": "Soldier",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "Mayor": {
   "id": "mayor",
   "name": "Mayor",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "Butler": {
   "id": "butler",
   "name": "Butler",
   "team": "outsider",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every",
   "first_night": 39,
   "other_night": 67
  },
  "Drunk": {
   "id": "drunk",
   "name": "Drunk",
   "team": "outsider",
   "wake": [
    "every",
    "first",
    "never",
    "other",
    "sometimes"
   ],
   "believes": true,
   "nights": "conditional",
   "impairs": true
  },
  "Recluse": {
   "id": "recluse",
   "name": "Recluse",
   "team": "outsider",
   "wake": [
    "never"
   ],
   "registers": [
    "demon",
    "minion"
   ]
  },
  "Saint": {
   "id": "saint",
   "name": "Saint",
   "team": "outsider",
   "wake": [
    "never"
   ]
  },
  "Poisoner": {
   "id": "poisoner",
   "name": "Poisoner",
   "team": "minion",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every",
   "impairs": true,
   "first_night": 17,
   "other_night": 7
  },
  "Spy": {
   "id": "spy",
   "name": "Spy",
   "team": "minion",
   "wake": [
    "every"
   ],
   "registers": [
    "outsider",
    "townsfolk"
   ],
   "nights": "every",
   "first_night": 49,
   "other_night": 68
  },
  "ScarletWoman": {
   "id": "scarletwoman",
   "name": "Scarlet Woman",
   "team": "minion",
   "wake": [
    "first",
    "sometimes"
   ],
   "nights": "conditional",
   "other_night": 19
  },
  "Baron": {
   "id": "baron",
   "name": "Baron",
   "team": "minion",
   "wake": [
    "first"
   ],
   "setup": [
    {
     "townsfolk": -2,
     "outsider": 2
    }
   ]
  },
  "Imp": {
   "id": "imp",
   "name": "Imp",
   "team": "demon",
   "wake": [
    "every",
    "first"
   ],
   "chooses": true,
   "nights": "other",
   "other_night": 24
  },
  "Godfather": {
   "id": "godfather",
   "name": "Godfather",
   "team": "minion",
   "wake": [
    "every",
    "first"
   ],
   "setup": [
    {
     "townsfolk": 1,
     "outsider": -1
    },
    {
     "townsfolk": -1,
     "outsider": 1
    }
   ],
   "chooses": true,
   "nights": "every",
   "first_night": 21,
   "other_night": 37
  },
  "DevilsAdvocate": {
   "id": "devilsadvocate",
   "name": "Devil's Advocate",
   "team": "minion",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every",
   "first_night": 22,
   "other_night": 13
  },
  "Assassin": {
   "id": "assassin",
   "name": "Assassin",
   "team": "minion",
   "wake": [
    "every",
    "first",
    "sometimes"
   ],
   "chooses": true,
   "nights": "conditional",
   "other_night": 36
  },
  "Zombuul": {
   "id": "zombuul",
   "name": "Zombuul",
   "team": "demon",
   "wake": [
    "every",
    "first",
    "sometimes"
   ],
   "chooses": true,
   "nights": "conditional",
   "other_night": 25
  },
  "Pukka": {
   "id": "pukka",
   "name": "Pukka",
   "team": "demon",
   "wake": [
    "every",
    "first"
   ],
   "chooses": true,
   "nights": "every",
   "first_night": 28,
   "other_night": 26
  },
  "Shabaloth": {
   "id": "shabaloth",
   "name": "Shabaloth",
   "team": "demon",
   "wake": [
    "every",
    "first"
   ],
   "chooses": true,
   "nights": "other",
   "other_night": 27
  },
  "Po": {
   "id": "po",
   "name": "Po",
   "team": "demon",
   "wake": [
    "every",
    "first"
   ],
   "chooses": true,
   "nights": "other",
   "other_night": 28
  },
  "Mastermind": {
   "id": "mastermind",
   "name": "Mastermind",
   "team": "minion",
   "wake": [
    "never"
   ],
   "modelled": false,
   "note": "it changes how the game is won rather than what happens on the board — no deaths, no readings, nothing to reason about. What it does do is let play carry on after the Demon is executed, and that much is modelled",
   "handled": "not",
   "settled": true
  },
  "Clockmaker": {
   "id": "clockmaker",
   "name": "Clockmaker",
   "team": "townsfolk",
   "wake": [
    "first"
   ],
   "nights": "first",
   "first_night": 41
  },
  "Dreamer": {
   "id": "dreamer",
   "name": "Dreamer",
   "team": "townsfolk",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every",
   "first_night": 42,
   "other_night": 56
  },
  "SnakeCharmer": {
   "id": "snakecharmer",
   "name": "Snake Charmer",
   "team": "townsfolk",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every",
   "impairs": true,
   "first_night": 20,
   "other_night": 11
  },
  "Mathematician": {
   "id": "mathematician",
   "name": "Mathematician",
   "team": "townsfolk",
   "wake": [
    "every"
   ],
   "nights": "every",
   "first_night": 52,
   "other_night": 71
  },
  "Flowergirl": {
   "id": "flowergirl",
   "name": "Flowergirl",
   "team": "townsfolk",
   "wake": [
    "other"
   ],
   "nights": "other",
   "other_night": 57
  },
  "TownCrier": {
   "id": "towncrier",
   "name": "Town Crier",
   "team": "townsfolk",
   "wake": [
    "other"
   ],
   "nights": "other",
   "other_night": 58
  },
  "Oracle": {
   "id": "oracle",
   "name": "Oracle",
   "team": "townsfolk",
   "wake": [
    "other"
   ],
   "nights": "other",
   "other_night": 59
  },
  "Savant": {
   "id": "savant",
   "name": "Savant",
   "team": "townsfolk",
   "wake": [
    "never"
   ],
   "modelled": false,
   "note": "its pair of statements is kept but not weighed: they can be anything at all, and checking arbitrary claims about a board is a different program from this one",
   "handled": "partly"
  },
  "Seamstress": {
   "id": "seamstress",
   "name": "Seamstress",
   "team": "townsfolk",
   "wake": [
    "never",
    "sometimes"
   ],
   "chooses": true,
   "nights": "conditional",
   "first_night": 43,
   "other_night": 60
  },
  "Philosopher": {
   "id": "philosopher",
   "name": "Philosopher",
   "team": "townsfolk",
   "wake": [
    "never",
    "sometimes"
   ],
   "chooses": true,
   "nights": "conditional",
   "impairs": true,
   "first_night": 2,
   "other_night": 2
  },
  "Artist": {
   "id": "artist",
   "name": "Artist",
   "team": "townsfolk",
   "wake": [
    "never"
   ],
   "modelled": false,
   "note": "its question is kept but not weighed — whatever the player thought to ask, which can be trivial or impossible",
   "handled": "partly"
  },
  "Juggler": {
   "id": "juggler",
   "name": "Juggler",
   "team": "townsfolk",
   "wake": [
    "never",
    "sometimes"
   ],
   "nights": "conditional",
   "other_night": 61
  },
  "Sage": {
   "id": "sage",
   "name": "Sage",
   "team": "townsfolk",
   "wake": [
    "never",
    "sometimes"
   ],
   "nights": "conditional",
   "other_night": 42
  },
  "Mutant": {
   "id": "mutant",
   "name": "Mutant",
   "team": "outsider",
   "wake": [
    "never"
   ],
   "modelled": false,
   "note": "madness leaves no mark on the board: being executed for breaking it looks like any other execution. If the table knows that is what happened, mark the seat as confirmed",
   "handled": "not",
   "settled": true
  },
  "Sweetheart": {
   "id": "sweetheart",
   "name": "Sweetheart",
   "team": "outsider",
   "wake": [
    "never"
   ],
   "impairs": true,
   "other_night": 41
  },
  "Barber": {
   "id": "barber",
   "name": "Barber",
   "team": "outsider",
   "wake": [
    "never"
   ],
   "other_night": 40
  },
  "Klutz": {
   "id": "klutz",
   "name": "Klutz",
   "team": "outsider",
   "wake": [
    "never"
   ]
  },
  "EvilTwin": {
   "id": "eviltwin",
   "name": "Evil Twin",
   "team": "minion",
   "wake": [
    "first"
   ],
   "nights": "first",
   "first_night": 23
  },
  "Witch": {
   "id": "witch",
   "name": "Witch",
   "team": "minion",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every",
   "first_night": 24,
   "other_night": 14
  },
  "Cerenovus": {
   "id": "cerenovus",
   "name": "Cerenovus",
   "team": "minion",
   "wake": [
    "every"
   ],
   "modelled": false,
   "note": "madness is a social constraint and leaves no mark of its own. What the table *can* see is somebody executed for breaking ceremadness, and marking that death says a Cerenovus is about — which is the only handle there is",
   "chooses": true,
   "nights": "every",
   "handled": "not",
   "settled": true,
   "first_night": 25,
   "other_night": 15
  },
  "PitHag": {
   "id": "pithag",
   "name": "Pit-Hag",
   "team": "minion",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every",
   "impairs": true,
   "other_night": 16
  },
  "FangGu": {
   "id": "fanggu",
   "name": "Fang Gu",
   "team": "demon",
   "wake": [
    "every",
    "first"
   ],
   "setup": [
    {
     "townsfolk": -1,
     "outsider": 1
    }
   ],
   "chooses": true,
   "nights": "other",
   "other_night": 29
  },
  "Vigormortis": {
   "id": "vigormortis",
   "name": "Vigormortis",
   "team": "demon",
   "wake": [
    "every",
    "first"
   ],
   "chooses": true,
   "nights": "other",
   "impairs": true,
   "other_night": 32
  },
  "NoDashii": {
   "id": "nodashii",
   "name": "No Dashii",
   "team": "demon",
   "wake": [
    "every",
    "first"
   ],
   "chooses": true,
   "nights": "other",
   "impairs": true,
   "other_night": 30
  },
  "Vortox": {
   "id": "vortox",
   "name": "Vortox",
   "team": "demon",
   "wake": [
    "every",
    "first"
   ],
   "chooses": true,
   "nights": "other",
   "other_night": 31
  },
  "Noble": {
   "id": "noble",
   "name": "Noble",
   "team": "townsfolk",
   "wake": [
    "first"
   ],
   "modelled": false,
   "note": "its first-night reading is not checked",
   "handled": "not",
   "first_night": 44
  },
  "Grandmother": {
   "id": "grandmother",
   "name": "Grandmother",
   "team": "townsfolk",
   "wake": [
    "first"
   ],
   "nights": "first",
   "first_night": 40,
   "other_night": 51
  },
  "Sailor": {
   "id": "sailor",
   "name": "Sailor",
   "team": "townsfolk",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every",
   "impairs": true,
   "first_night": 11,
   "other_night": 4
  },
  "Exorcist": {
   "id": "exorcist",
   "name": "Exorcist",
   "team": "townsfolk",
   "wake": [
    "every",
    "other"
   ],
   "chooses": true,
   "nights": "other",
   "other_night": 21
  },
  "Innkeeper": {
   "id": "innkeeper",
   "name": "Innkeeper",
   "team": "townsfolk",
   "wake": [
    "every",
    "other"
   ],
   "chooses": true,
   "nights": "other",
   "impairs": true,
   "other_night": 9
  },
  "Courtier": {
   "id": "courtier",
   "name": "Courtier",
   "team": "townsfolk",
   "wake": [
    "every",
    "first",
    "sometimes"
   ],
   "nights": "conditional",
   "impairs": true,
   "first_night": 19,
   "other_night": 8
  },
  "Professor": {
   "id": "professor",
   "name": "Professor",
   "team": "townsfolk",
   "wake": [
    "other",
    "sometimes"
   ],
   "chooses": true,
   "nights": "conditional",
   "other_night": 43
  },
  "Gambler": {
   "id": "gambler",
   "name": "Gambler",
   "team": "townsfolk",
   "wake": [
    "every",
    "other"
   ],
   "chooses": true,
   "nights": "other",
   "other_night": 10
  },
  "Gossip": {
   "id": "gossip",
   "name": "Gossip",
   "team": "townsfolk",
   "wake": [
    "never"
   ],
   "other_night": 38
  },
  "Minstrel": {
   "id": "minstrel",
   "name": "Minstrel",
   "team": "townsfolk",
   "wake": [
    "never"
   ],
   "impairs": true
  },
  "Chambermaid": {
   "id": "chambermaid",
   "name": "Chambermaid",
   "team": "townsfolk",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every",
   "first_night": 51,
   "other_night": 70
  },
  "Pacifist": {
   "id": "pacifist",
   "name": "Pacifist",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "TeaLady": {
   "id": "tealady",
   "name": "Tea Lady",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "Fool": {
   "id": "fool",
   "name": "Fool",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "Goon": {
   "id": "goon",
   "name": "Goon",
   "team": "outsider",
   "wake": [
    "never"
   ],
   "alignment_open": true,
   "impairs": true
  },
  "Tinker": {
   "id": "tinker",
   "name": "Tinker",
   "team": "outsider",
   "wake": [
    "never"
   ],
   "other_night": 49
  },
  "Moonchild": {
   "id": "moonchild",
   "name": "Moonchild",
   "team": "outsider",
   "wake": [
    "never"
   ],
   "chooses": true,
   "other_night": 50
  },
  "Lunatic": {
   "id": "lunatic",
   "name": "Lunatic",
   "team": "outsider",
   "wake": [
    "every",
    "first",
    "never",
    "other",
    "sometimes"
   ],
   "believes": true,
   "believes_from": [
    "demon"
   ],
   "chooses": true,
   "nights": "conditional",
   "impairs": true,
   "first_night": 8,
   "other_night": 20
  },
  "Ogre": {
   "id": "ogre",
   "name": "Ogre",
   "team": "outsider",
   "wake": [
    "first"
   ],
   "modelled": false,
   "note": "it turns evil on the first night, which is a change of side the solver would have to be told about",
   "handled": "not"
  },
  "Atheist": {
   "id": "atheist",
   "name": "Atheist",
   "team": "townsfolk",
   "wake": [
    "never"
   ],
   "modelled": false,
   "note": "with an Atheist in play the Storyteller may break the rules, so there may be no legal world at all",
   "handled": "not"
  },
  "Legion": {
   "id": "legion",
   "name": "Legion",
   "team": "demon",
   "wake": [
    "never"
   ],
   "modelled": false,
   "note": "most of the table is evil, so every team count the search prunes on is wrong",
   "handled": "not",
   "other_night": 23
  },
  "Riot": {
   "id": "riot",
   "name": "Riot",
   "team": "demon",
   "wake": [
    "never"
   ],
   "modelled": false,
   "note": "every Minion is a Demon, and days work differently",
   "handled": "not"
  },
  "Marionette": {
   "id": "marionette",
   "name": "Marionette",
   "team": "minion",
   "wake": [
    "every",
    "first",
    "never",
    "other",
    "sometimes"
   ],
   "believes": true,
   "believes_from": [
    "townsfolk",
    "outsider"
   ],
   "modelled": false,
   "note": "it believes it is a good character, like the Drunk, but the machinery for that is still tied to the Drunk alone",
   "nights": "conditional",
   "impairs": true,
   "handled": "not",
   "first_night": 12
  },
  "Sentinel": {
   "id": "sentinel",
   "name": "Sentinel",
   "team": "fabled",
   "wake": [
    "never"
   ],
   "setup": [
    {
     "townsfolk": 1,
     "outsider": -1
    },
    {},
    {
     "townsfolk": -1,
     "outsider": 1
    }
   ],
   "seated": false
  }
 },
 "scripts": {
  "Trouble Brewing": [
   "Washerwoman",
   "Librarian",
   "Investigator",
   "Chef",
   "Empath",
   "FortuneTeller",
   "Undertaker",
   "Monk",
   "Ravenkeeper",
   "Virgin",
   "Slayer",
   "Soldier",
   "Mayor",
   "Butler",
   "Drunk",
   "Recluse",
   "Saint",
   "Poisoner",
   "Spy",
   "ScarletWoman",
   "Baron",
   "Imp"
  ],
  "Bad Moon Rising": [
   "Grandmother",
   "Sailor",
   "Chambermaid",
   "Exorcist",
   "Innkeeper",
   "Gambler",
   "Gossip",
   "Courtier",
   "Professor",
   "Minstrel",
   "TeaLady",
   "Pacifist",
   "Fool",
   "Tinker",
   "Moonchild",
   "Goon",
   "Lunatic",
   "Godfather",
   "DevilsAdvocate",
   "Assassin",
   "Mastermind",
   "Zombuul",
   "Pukka",
   "Shabaloth",
   "Po"
  ],
  "Sects & Violets": [
   "Clockmaker",
   "Dreamer",
   "SnakeCharmer",
   "Mathematician",
   "Flowergirl",
   "TownCrier",
   "Oracle",
   "Savant",
   "Seamstress",
   "Philosopher",
   "Artist",
   "Juggler",
   "Sage",
   "Mutant",
   "Sweetheart",
   "Barber",
   "Klutz",
   "EvilTwin",
   "Witch",
   "Cerenovus",
   "PitHag",
   "FangGu",
   "Vigormortis",
   "NoDashii",
   "Vortox"
  ]
 },
 "setup": {
  "5": [
   3,
   0,
   1,
   1
  ],
  "6": [
   3,
   1,
   1,
   1
  ],
  "7": [
   5,
   0,
   1,
   1
  ],
  "8": [
   5,
   1,
   1,
   1
  ],
  "9": [
   5,
   2,
   1,
   1
  ],
  "10": [
   7,
   0,
   2,
   1
  ],
  "11": [
   7,
   1,
   2,
   1
  ],
  "12": [
   7,
   2,
   2,
   1
  ],
  "13": [
   9,
   0,
   3,
   1
  ],
  "14": [
   9,
   1,
   3,
   1
  ],
  "15": [
   9,
   2,
   3,
   1
  ]
 },
 "wakePatterns": [
  "never",
  "first",
  "every",
  "other",
  "sometimes"
 ],
 "wakeLabels": {
  "never": "Never wakes",
  "first": "Only the first night",
  "every": "Every night",
  "other": "Every night but the first",
  "sometimes": "Only sometimes"
 }
};
