// Generated by tools/gen_characters.py — do not edit by hand.
//
// The catalogue is fifty-seven characters with a dozen fields
// each. Transcribing that into a second language by hand is a
// way of introducing mistakes rather than a way of porting, so
// the data is generated and only the logic is written twice.
//
// A field is present only when it differs from the ordinary
// case, so what you read here is what is unusual about each
// character.

export const DATA = {
 "characters": {
  "Washerwoman": {
   "id": "washerwoman",
   "name": "Washerwoman",
   "team": "townsfolk",
   "wake": [
    "first"
   ],
   "nights": "first"
  },
  "Librarian": {
   "id": "librarian",
   "name": "Librarian",
   "team": "townsfolk",
   "wake": [
    "first"
   ],
   "nights": "first"
  },
  "Investigator": {
   "id": "investigator",
   "name": "Investigator",
   "team": "townsfolk",
   "wake": [
    "first"
   ],
   "nights": "first"
  },
  "Chef": {
   "id": "chef",
   "name": "Chef",
   "team": "townsfolk",
   "wake": [
    "first"
   ],
   "nights": "first"
  },
  "Empath": {
   "id": "empath",
   "name": "Empath",
   "team": "townsfolk",
   "wake": [
    "every"
   ],
   "nights": "every"
  },
  "FortuneTeller": {
   "id": "fortuneteller",
   "name": "Fortune Teller",
   "team": "townsfolk",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every"
  },
  "Undertaker": {
   "id": "undertaker",
   "name": "Undertaker",
   "team": "townsfolk",
   "wake": [
    "every",
    "other",
    "sometimes"
   ],
   "nights": "conditional"
  },
  "Monk": {
   "id": "monk",
   "name": "Monk",
   "team": "townsfolk",
   "wake": [
    "every",
    "other"
   ],
   "chooses": true,
   "nights": "other"
  },
  "Ravenkeeper": {
   "id": "ravenkeeper",
   "name": "Ravenkeeper",
   "team": "townsfolk",
   "wake": [
    "never",
    "sometimes"
   ],
   "chooses": true,
   "nights": "conditional"
  },
  "Virgin": {
   "id": "virgin",
   "name": "Virgin",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "Slayer": {
   "id": "slayer",
   "name": "Slayer",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "Soldier": {
   "id": "soldier",
   "name": "Soldier",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "Mayor": {
   "id": "mayor",
   "name": "Mayor",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "Butler": {
   "id": "butler",
   "name": "Butler",
   "team": "outsider",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every"
  },
  "Drunk": {
   "id": "drunk",
   "name": "Drunk",
   "team": "outsider",
   "wake": [
    "every",
    "first",
    "never",
    "other",
    "sometimes"
   ],
   "believes": true,
   "nights": "conditional"
  },
  "Recluse": {
   "id": "recluse",
   "name": "Recluse",
   "team": "outsider",
   "wake": [
    "never"
   ],
   "registers": [
    "demon",
    "minion"
   ]
  },
  "Saint": {
   "id": "saint",
   "name": "Saint",
   "team": "outsider",
   "wake": [
    "never"
   ]
  },
  "Poisoner": {
   "id": "poisoner",
   "name": "Poisoner",
   "team": "minion",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every"
  },
  "Spy": {
   "id": "spy",
   "name": "Spy",
   "team": "minion",
   "wake": [
    "every"
   ],
   "registers": [
    "outsider",
    "townsfolk"
   ],
   "nights": "every"
  },
  "ScarletWoman": {
   "id": "scarletwoman",
   "name": "Scarlet Woman",
   "team": "minion",
   "wake": [
    "first",
    "sometimes"
   ],
   "nights": "conditional"
  },
  "Baron": {
   "id": "baron",
   "name": "Baron",
   "team": "minion",
   "wake": [
    "first"
   ],
   "setup": [
    {
     "townsfolk": -2,
     "outsider": 2
    }
   ]
  },
  "Imp": {
   "id": "imp",
   "name": "Imp",
   "team": "demon",
   "wake": [
    "every",
    "first"
   ],
   "chooses": true,
   "nights": "other"
  },
  "Godfather": {
   "id": "godfather",
   "name": "Godfather",
   "team": "minion",
   "wake": [
    "every",
    "first"
   ],
   "setup": [
    {
     "townsfolk": 1,
     "outsider": -1
    },
    {
     "townsfolk": -1,
     "outsider": 1
    }
   ],
   "chooses": true,
   "nights": "every"
  },
  "DevilsAdvocate": {
   "id": "devilsadvocate",
   "name": "Devil's Advocate",
   "team": "minion",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every"
  },
  "Assassin": {
   "id": "assassin",
   "name": "Assassin",
   "team": "minion",
   "wake": [
    "every",
    "first",
    "sometimes"
   ],
   "chooses": true,
   "nights": "conditional"
  },
  "Zombuul": {
   "id": "zombuul",
   "name": "Zombuul",
   "team": "demon",
   "wake": [
    "every",
    "first",
    "sometimes"
   ],
   "chooses": true,
   "nights": "conditional"
  },
  "Pukka": {
   "id": "pukka",
   "name": "Pukka",
   "team": "demon",
   "wake": [
    "every",
    "first"
   ],
   "chooses": true,
   "nights": "every"
  },
  "Shabaloth": {
   "id": "shabaloth",
   "name": "Shabaloth",
   "team": "demon",
   "wake": [
    "every",
    "first"
   ],
   "chooses": true,
   "nights": "other"
  },
  "Po": {
   "id": "po",
   "name": "Po",
   "team": "demon",
   "wake": [
    "every",
    "first"
   ],
   "chooses": true,
   "nights": "other"
  },
  "Mastermind": {
   "id": "mastermind",
   "name": "Mastermind",
   "team": "minion",
   "wake": [
    "never"
   ],
   "modelled": false,
   "note": "it changes how the game is won rather than what happens on the board — no deaths, no readings, nothing to reason about. What it does do is let play carry on after the Demon is executed, and that much is modelled"
  },
  "Noble": {
   "id": "noble",
   "name": "Noble",
   "team": "townsfolk",
   "wake": [
    "first"
   ],
   "modelled": false,
   "note": "its first-night reading is not checked"
  },
  "Clockmaker": {
   "id": "clockmaker",
   "name": "Clockmaker",
   "team": "townsfolk",
   "wake": [
    "first"
   ],
   "modelled": false,
   "note": "its first-night reading is not checked"
  },
  "Grandmother": {
   "id": "grandmother",
   "name": "Grandmother",
   "team": "townsfolk",
   "wake": [
    "first"
   ],
   "nights": "first"
  },
  "Sailor": {
   "id": "sailor",
   "name": "Sailor",
   "team": "townsfolk",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every"
  },
  "Exorcist": {
   "id": "exorcist",
   "name": "Exorcist",
   "team": "townsfolk",
   "wake": [
    "every",
    "other"
   ],
   "chooses": true,
   "nights": "other"
  },
  "Innkeeper": {
   "id": "innkeeper",
   "name": "Innkeeper",
   "team": "townsfolk",
   "wake": [
    "every",
    "other"
   ],
   "chooses": true,
   "nights": "other"
  },
  "Courtier": {
   "id": "courtier",
   "name": "Courtier",
   "team": "townsfolk",
   "wake": [
    "every",
    "first",
    "sometimes"
   ],
   "nights": "conditional"
  },
  "Professor": {
   "id": "professor",
   "name": "Professor",
   "team": "townsfolk",
   "wake": [
    "other",
    "sometimes"
   ],
   "chooses": true,
   "nights": "conditional"
  },
  "Gambler": {
   "id": "gambler",
   "name": "Gambler",
   "team": "townsfolk",
   "wake": [
    "every",
    "other"
   ],
   "chooses": true,
   "nights": "other"
  },
  "Gossip": {
   "id": "gossip",
   "name": "Gossip",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "Minstrel": {
   "id": "minstrel",
   "name": "Minstrel",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "Chambermaid": {
   "id": "chambermaid",
   "name": "Chambermaid",
   "team": "townsfolk",
   "wake": [
    "every"
   ],
   "chooses": true,
   "nights": "every"
  },
  "Pacifist": {
   "id": "pacifist",
   "name": "Pacifist",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "TeaLady": {
   "id": "tealady",
   "name": "Tea Lady",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "Fool": {
   "id": "fool",
   "name": "Fool",
   "team": "townsfolk",
   "wake": [
    "never"
   ]
  },
  "Goon": {
   "id": "goon",
   "name": "Goon",
   "team": "outsider",
   "wake": [
    "never"
   ],
   "alignment_open": true
  },
  "Tinker": {
   "id": "tinker",
   "name": "Tinker",
   "team": "outsider",
   "wake": [
    "never"
   ]
  },
  "Moonchild": {
   "id": "moonchild",
   "name": "Moonchild",
   "team": "outsider",
   "wake": [
    "never"
   ],
   "chooses": true
  },
  "Lunatic": {
   "id": "lunatic",
   "name": "Lunatic",
   "team": "outsider",
   "wake": [
    "every",
    "first",
    "never",
    "other",
    "sometimes"
   ],
   "believes": true,
   "believes_from": [
    "demon"
   ],
   "chooses": true,
   "nights": "conditional"
  },
  "Artist": {
   "id": "artist",
   "name": "Artist",
   "team": "townsfolk",
   "wake": [
    "never",
    "sometimes"
   ],
   "modelled": false,
   "note": "its question is not modelled"
  },
  "Ogre": {
   "id": "ogre",
   "name": "Ogre",
   "team": "outsider",
   "wake": [
    "first"
   ],
   "modelled": false,
   "note": "it turns evil on the first night, which is a change of side the solver would have to be told about"
  },
  "Atheist": {
   "id": "atheist",
   "name": "Atheist",
   "team": "townsfolk",
   "wake": [
    "never"
   ],
   "modelled": false,
   "note": "with an Atheist in play the Storyteller may break the rules, so there may be no legal world at all"
  },
  "Legion": {
   "id": "legion",
   "name": "Legion",
   "team": "demon",
   "wake": [
    "never"
   ],
   "modelled": false,
   "note": "most of the table is evil, so every team count the search prunes on is wrong"
  },
  "Riot": {
   "id": "riot",
   "name": "Riot",
   "team": "demon",
   "wake": [
    "never"
   ],
   "modelled": false,
   "note": "every Minion is a Demon, and days work differently"
  },
  "Marionette": {
   "id": "marionette",
   "name": "Marionette",
   "team": "minion",
   "wake": [
    "every",
    "first",
    "never",
    "other",
    "sometimes"
   ],
   "believes": true,
   "believes_from": [
    "townsfolk",
    "outsider"
   ],
   "modelled": false,
   "note": "it believes it is a good character, like the Drunk, but the machinery for that is still tied to the Drunk alone",
   "nights": "conditional"
  },
  "Sentinel": {
   "id": "sentinel",
   "name": "Sentinel",
   "team": "fabled",
   "wake": [
    "never"
   ],
   "setup": [
    {
     "townsfolk": 1,
     "outsider": -1
    },
    {},
    {
     "townsfolk": -1,
     "outsider": 1
    }
   ],
   "seated": false
  }
 },
 "scripts": {
  "Trouble Brewing": [
   "Washerwoman",
   "Librarian",
   "Investigator",
   "Chef",
   "Empath",
   "FortuneTeller",
   "Undertaker",
   "Monk",
   "Ravenkeeper",
   "Virgin",
   "Slayer",
   "Soldier",
   "Mayor",
   "Butler",
   "Drunk",
   "Recluse",
   "Saint",
   "Poisoner",
   "Spy",
   "ScarletWoman",
   "Baron",
   "Imp"
  ],
  "Bad Moon Rising": [
   "Grandmother",
   "Sailor",
   "Chambermaid",
   "Exorcist",
   "Innkeeper",
   "Gambler",
   "Gossip",
   "Courtier",
   "Professor",
   "Minstrel",
   "TeaLady",
   "Pacifist",
   "Fool",
   "Tinker",
   "Moonchild",
   "Goon",
   "Lunatic",
   "Godfather",
   "DevilsAdvocate",
   "Assassin",
   "Mastermind",
   "Zombuul",
   "Pukka",
   "Shabaloth",
   "Po"
  ]
 },
 "setup": {
  "5": [
   3,
   0,
   1,
   1
  ],
  "6": [
   3,
   1,
   1,
   1
  ],
  "7": [
   5,
   0,
   1,
   1
  ],
  "8": [
   5,
   1,
   1,
   1
  ],
  "9": [
   5,
   2,
   1,
   1
  ],
  "10": [
   7,
   0,
   2,
   1
  ],
  "11": [
   7,
   1,
   2,
   1
  ],
  "12": [
   7,
   2,
   2,
   1
  ],
  "13": [
   9,
   0,
   3,
   1
  ],
  "14": [
   9,
   1,
   3,
   1
  ],
  "15": [
   9,
   2,
   3,
   1
  ]
 },
 "wakePatterns": [
  "never",
  "first",
  "every",
  "other",
  "sometimes"
 ],
 "wakeLabels": {
  "never": "Never wakes",
  "first": "Only the first night",
  "every": "Every night",
  "other": "Every night but the first",
  "sometimes": "Only sometimes"
 }
};
