"""Write the character data out as a JavaScript module.

The catalogue is fifty-seven characters with a dozen fields each, and
transcribing that by hand into a second language is a way of introducing
mistakes rather than a way of porting. So the data is generated and only
the *logic* is written twice — which is the part worth checking, and the
part the conformance corpus checks.

    python tools/gen_characters.py     # rewrite js/characters.mjs

Run it after changing the catalogue or the built-in scripts, and read the
diff. If the JavaScript solver ever disagrees with Python about what a
character is, this file being stale is the first thing to rule out.
"""

import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from botc import scripts                                     # noqa: E402
from botc.catalogue import CHARACTERS, WAKE_LABELS, WAKE_PATTERNS  # noqa: E402
from botc.roles import SETUP                                  # noqa: E402

OUT = HERE.parent / "js" / "characters.mjs"

# Fields left at their default are left out, so the generated file reads
# as the catalogue does: what is unusual about each character, not a
# repetition of what is ordinary.
DEFAULTS = {
    "registers": frozenset(), "setup": (), "believes": False,
    "believes_from": ("townsfolk",), "modelled": True, "note": "",
    "chooses": False, "alignment_open": False, "nights": "never",
    "seated": True, "impairs": False, "handled": "fully", "settled": False,
    "first_night": 0, "other_night": 0,
}


def check_defaults_cover_every_field():
    """Every field has to be named above, or it is silently dropped.

    A field missing from the table is left out of the generated file for
    *every* character, default or not — so adding one to the catalogue
    and forgetting it here means the JavaScript quietly never sees it.
    That happened with `impairs`, and the conformance corpus caught it
    one board later.
    """
    from botc.catalogue import Character
    missing = [f for f in Character._fields
               if f not in DEFAULTS and f not in ("key", "id", "name",
                                                  "team", "wake")]
    if missing:
        raise SystemExit(
            f"tools/gen_characters.py does not know about {missing} — "
            f"add them to DEFAULTS or they will be dropped silently.")


def plain(value):
    if isinstance(value, (frozenset, set)):
        return sorted(value)
    if isinstance(value, tuple):
        return [plain(v) for v in value]
    return value


def character(c):
    out = {"id": c.id, "name": c.name, "team": c.team,
           "wake": sorted(c.wake)}
    for field, default in DEFAULTS.items():
        value = getattr(c, field)
        if value != default:
            out[field] = plain(value)
    return out


def build():
    check_defaults_cover_every_field()
    data = {
        "characters": {key: character(c) for key, c in CHARACTERS.items()},
        "scripts": {name: list(s.keys)
                    for name, s in scripts.BUILT_IN.items()},
        "setup": {str(n): list(counts) for n, counts in SETUP.items()},
        "wakePatterns": list(WAKE_PATTERNS),
        "wakeLabels": dict(WAKE_LABELS),
    }
    body = json.dumps(data, indent=1, ensure_ascii=False)
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(
        "// Generated by tools/gen_characters.py — do not edit by hand.\n"
        "//\n"
        "// The catalogue is fifty-seven characters with a dozen fields\n"
        "// each. Transcribing that into a second language by hand is a\n"
        "// way of introducing mistakes rather than a way of porting, so\n"
        "// the data is generated and only the logic is written twice.\n"
        "//\n"
        "// A field is present only when it differs from the ordinary\n"
        "// case, so what you read here is what is unusual about each\n"
        "// character.\n\n"
        "export const DATA = " + body + ";\n")
    print(f"{len(data['characters'])} characters and "
          f"{len(data['scripts'])} scripts written to "
          f"{OUT.relative_to(HERE.parent)}")
    print(f"   {OUT.stat().st_size / 1024:.0f} kB")


if __name__ == "__main__":
    build()
